### ISSUE TITLE
Packer crashing when using version 1.0.0 of tart plugin

### ISSUE THREAD

**Issue by Zehina** [cirruslabs/packer-plugin-tart#53]
## Description
When attempting to build a mac VM today using packer and the tart plugin. The build failed with:
```
2023/03/01 10:32:10 ConfigSpec failed: gob: type cty.Type has no exported fields
2023/03/01 10:32:10 waiting for all plugin processes to complete...
2023/03/01 10:32:10 /Users/ci/.config/packer/plugins/github.com/cirruslabs/tart/packer-plugin-tart_v1.0.0_x5.0_darwin_arm64: plugin process exited
panic: ConfigSpec failed: gob: type cty.Type has no exported fields [recovered]
	panic: ConfigSpec failed: gob: type cty.Type has no exported fields

goroutine 1 [running]:
log.Panic({0x14000f1e798?, 0x1000000000090?, 0x1?})
	/Users/runner/hostedtoolcache/go/1.18.9/x64/src/log/log.go:385 +0x68
github.com/hashicorp/packer/packer.(*cmdBuilder).checkExit(0x140004a8790?, {0x106f924c0, 0x140004a87c0}, 0x0)
	/Users/runner/work/packer/packer/packer/cmd_builder.go:47 +0x84
github.com/hashicorp/packer/packer.(*cmdBuilder).ConfigSpec.func1()
	/Users/runner/work/packer/packer/packer/cmd_builder.go:19 +0x44
panic({0x106f924c0, 0x140004a87c0})
	/Users/runner/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:838 +0x204
github.com/hashicorp/packer-plugin-sdk/rpc.(*commonClient).ConfigSpec(0x14000682220)
	/Users/runner/go/pkg/mod/github.com/hashicorp/packer-plugin-sdk@v0.3.2/rpc/common.go:44 +0x24c
github.com/hashicorp/packer/packer.(*cmdBuilder).ConfigSpec(0x0?)
	/Users/runner/work/packer/packer/packer/cmd_builder.go:22 +0x5c
github.com/hashicorp/packer/hcl2template.decodeHCL2Spec({0x10809f9d8, 0x14000e00d20}, 0x10625bac8?, {0x1145c34d8?, 0x1400000c9c0?})
	/Users/runner/work/packer/packer/hcl2template/decode.go:17 +0x3c
github.com/hashicorp/packer/hcl2template.(*PackerConfig).startBuilder(0x140005ac140, {{{0x140001d479f, 0x8}, {0x140001d47a8, 0x8}}, {0x0, 0x0}, {0x10809f9d8, 0x14000e00d20}}, 0x1400014eb10)
	/Users/runner/work/packer/packer/hcl2template/types.source.go:116 +0x148
github.com/hashicorp/packer/hcl2template.(*PackerConfig).GetBuilds(0x140005ac140, {{0x0, 0x0, 0x0}, {0x140007ea030, 0x1, 0x1}, 0x0, 0x0, {0x0, ...}, ...})
	/Users/runner/work/packer/packer/hcl2template/types.packer_config.go:654 +0xd68
github.com/hashicorp/packer/command.(*BuildCommand).RunContext(0x14000e00b10, {0x10809f038?, 0x14000706600}, 0x140003d7b00)
	/Users/runner/work/packer/packer/command/build.go:110 +0x1a8
github.com/hashicorp/packer/command.(*BuildCommand).Run(0x14000e00b10, {0x140001a4020, 0x6, 0x6})
	/Users/runner/work/packer/packer/command/build.go:38 +0xb0
github.com/mitchellh/cli.(*CLI).Run(0x140004163c0)
	/Users/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x4cc
main.wrappedMain()
	/Users/runner/work/packer/packer/main.go:262 +0xa40
main.realMain()
	/Users/runner/work/packer/packer/main.go:49 +0xb8
main.main()
	/Users/runner/work/packer/packer/main.go:35 +0x20
!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.
[1]: https://github.com/hashicorp/packer/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
- This seems to be an issue with Packer but yet it doesn't happen with version **0.6.3** and earlier of the tart plugin
 ## Packer version
**1.8.4**
**1.8.5**
**1.9.0-dev**

## Versions affected
**1.0.0**

## Workaround
Changed plugin version to only use **0.6.3** and less for now
```
packer {
  required_plugins {
    tart = {
      version = "<= 0.6.3"
      source  = "github.com/cirruslabs/tart"
    }
  }
}
```

**Comment by edigaryev** [comment]
Hello Ali, thanks for reporting this!

Please check out the [new 1.0.1 release](https://github.com/cirruslabs/packer-plugin-tart/releases/tag/v1.0.1), it should fix the issue 👌
